### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by arjunguha** [umass-compsci220/ocelot-settings#3]
Should we use Travis or CircleCI?

**Comment by sp1tz** [comment]
EJS uses Travis, so stick with that for consistency perhaps. For now it just needs to run `npm t` (that builds and then runs the tests on the compiled JS).

**Comment by sp1tz** [comment]
I was trying to setup Travis, but I don't have valid permissions for `umass-compsci220/ocelot-settings`:
>You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself.
